//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Google_ProtocolBuffers_AbstractMessageLite_MyLib_CGPlayerCmd_MyLib_CGPlayerCmd_BuilderWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>), typeof(System.Object), "AbstractMessageLite_MyLib_CGPlayerCmd_MyLib_CGPlayerCmd_Builder");
		L.RegFunction("CreateBuilderForType", CreateBuilderForType);
		L.RegFunction("ToBuilder", ToBuilder);
		L.RegFunction("WriteTo", WriteTo);
		L.RegFunction("PrintTo", PrintTo);
		L.RegFunction("ToByteString", ToByteString);
		L.RegFunction("ToByteArray", ToByteArray);
		L.RegFunction("WriteDelimitedTo", WriteDelimitedTo);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("DefaultInstanceForType", get_DefaultInstanceForType, null);
		L.RegVar("IsInitialized", get_IsInitialized, null);
		L.RegVar("SerializedSize", get_SerializedSize, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateBuilderForType(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder> obj = (Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>)ToLua.CheckObject<Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>>(L, 1);
			MyLib.CGPlayerCmd.Builder o = obj.CreateBuilderForType();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToBuilder(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder> obj = (Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>)ToLua.CheckObject<Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>>(L, 1);
			MyLib.CGPlayerCmd.Builder o = obj.ToBuilder();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WriteTo(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<Google.ProtocolBuffers.CodedOutputStream>(L, 2))
			{
				Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder> obj = (Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>)ToLua.CheckObject<Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>>(L, 1);
				Google.ProtocolBuffers.CodedOutputStream arg0 = (Google.ProtocolBuffers.CodedOutputStream)ToLua.ToObject(L, 2);
				obj.WriteTo(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.Stream>(L, 2))
			{
				Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder> obj = (Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>)ToLua.CheckObject<Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>>(L, 1);
				System.IO.Stream arg0 = (System.IO.Stream)ToLua.ToObject(L, 2);
				obj.WriteTo(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>.WriteTo");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PrintTo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder> obj = (Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>)ToLua.CheckObject<Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>>(L, 1);
			System.IO.TextWriter arg0 = (System.IO.TextWriter)ToLua.CheckObject<System.IO.TextWriter>(L, 2);
			obj.PrintTo(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToByteString(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder> obj = (Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>)ToLua.CheckObject<Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>>(L, 1);
			Google.ProtocolBuffers.ByteString o = obj.ToByteString();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToByteArray(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder> obj = (Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>)ToLua.CheckObject<Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>>(L, 1);
			byte[] o = obj.ToByteArray();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WriteDelimitedTo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder> obj = (Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>)ToLua.CheckObject<Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>>(L, 1);
			System.IO.Stream arg0 = (System.IO.Stream)ToLua.CheckObject<System.IO.Stream>(L, 2);
			obj.WriteDelimitedTo(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DefaultInstanceForType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder> obj = (Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>)o;
			MyLib.CGPlayerCmd ret = obj.DefaultInstanceForType;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index DefaultInstanceForType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsInitialized(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder> obj = (Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>)o;
			bool ret = obj.IsInitialized;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index IsInitialized on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SerializedSize(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder> obj = (Google.ProtocolBuffers.AbstractMessageLite<MyLib.CGPlayerCmd,MyLib.CGPlayerCmd.Builder>)o;
			int ret = obj.SerializedSize;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index SerializedSize on a nil value");
		}
	}
}

