//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaHelperWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("LuaHelper");
		L.RegFunction("GetPanelManager", GetPanelManager);
		L.RegFunction("GetLuaManager", GetLuaManager);
		L.RegFunction("GetNetworkScene", GetNetworkScene);
		L.RegFunction("GetSaveGame", GetSaveGame);
		L.RegFunction("GetLogic", GetLogic);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPanelManager(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			PanelManager o = LuaHelper.GetPanelManager();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLuaManager(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			LuaManager o = LuaHelper.GetLuaManager();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetNetworkScene(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			NetworkScene o = LuaHelper.GetNetworkScene();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSaveGame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			SaveGame o = LuaHelper.GetSaveGame();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLogic(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			Logic o = LuaHelper.GetLogic();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

