//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MyLib_GCPlayerCmd_BuilderWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MyLib.GCPlayerCmd.Builder), typeof(Google.ProtocolBuffers.GeneratedBuilderLite<MyLib.GCPlayerCmd,MyLib.GCPlayerCmd.Builder>));
		L.RegFunction("Clear", Clear);
		L.RegFunction("Clone", Clone);
		L.RegFunction("BuildPartial", BuildPartial);
		L.RegFunction("MergeFrom", MergeFrom);
		L.RegFunction("SetResult", SetResult);
		L.RegFunction("ClearResult", ClearResult);
		L.RegFunction("SetAvatarInfo", SetAvatarInfo);
		L.RegFunction("MergeAvatarInfo", MergeAvatarInfo);
		L.RegFunction("ClearAvatarInfo", ClearAvatarInfo);
		L.RegFunction("SetDamageInfo", SetDamageInfo);
		L.RegFunction("MergeDamageInfo", MergeDamageInfo);
		L.RegFunction("ClearDamageInfo", ClearDamageInfo);
		L.RegFunction("SetSkillAction", SetSkillAction);
		L.RegFunction("MergeSkillAction", MergeSkillAction);
		L.RegFunction("ClearSkillAction", ClearSkillAction);
		L.RegFunction("SetBuffInfo", SetBuffInfo);
		L.RegFunction("MergeBuffInfo", MergeBuffInfo);
		L.RegFunction("ClearBuffInfo", ClearBuffInfo);
		L.RegFunction("SetEntityInfo", SetEntityInfo);
		L.RegFunction("MergeEntityInfo", MergeEntityInfo);
		L.RegFunction("ClearEntityInfo", ClearEntityInfo);
		L.RegFunction("SetPickAction", SetPickAction);
		L.RegFunction("MergePickAction", MergePickAction);
		L.RegFunction("ClearPickAction", ClearPickAction);
		L.RegFunction("SetLeftTime", SetLeftTime);
		L.RegFunction("ClearLeftTime", ClearLeftTime);
		L.RegFunction("SetRoomInfo", SetRoomInfo);
		L.RegFunction("MergeRoomInfo", MergeRoomInfo);
		L.RegFunction("ClearRoomInfo", ClearRoomInfo);
		L.RegFunction("SetNews", SetNews);
		L.RegFunction("ClearNews", ClearNews);
		L.RegFunction("SetActorId", SetActorId);
		L.RegFunction("ClearActorId", ClearActorId);
		L.RegFunction("SetFrameId", SetFrameId);
		L.RegFunction("ClearFrameId", ClearFrameId);
		L.RegFunction("SetRunInFrame", SetRunInFrame);
		L.RegFunction("ClearRunInFrame", ClearRunInFrame);
		L.RegFunction("New", _CreateMyLib_GCPlayerCmd_Builder);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("DefaultInstanceForType", get_DefaultInstanceForType, null);
		L.RegVar("HasResult", get_HasResult, null);
		L.RegVar("Result", get_Result, set_Result);
		L.RegVar("HasAvatarInfo", get_HasAvatarInfo, null);
		L.RegVar("AvatarInfo", get_AvatarInfo, set_AvatarInfo);
		L.RegVar("HasDamageInfo", get_HasDamageInfo, null);
		L.RegVar("DamageInfo", get_DamageInfo, set_DamageInfo);
		L.RegVar("HasSkillAction", get_HasSkillAction, null);
		L.RegVar("SkillAction", get_SkillAction, set_SkillAction);
		L.RegVar("HasBuffInfo", get_HasBuffInfo, null);
		L.RegVar("BuffInfo", get_BuffInfo, set_BuffInfo);
		L.RegVar("HasEntityInfo", get_HasEntityInfo, null);
		L.RegVar("EntityInfo", get_EntityInfo, set_EntityInfo);
		L.RegVar("HasPickAction", get_HasPickAction, null);
		L.RegVar("PickAction", get_PickAction, set_PickAction);
		L.RegVar("HasLeftTime", get_HasLeftTime, null);
		L.RegVar("LeftTime", get_LeftTime, set_LeftTime);
		L.RegVar("HasRoomInfo", get_HasRoomInfo, null);
		L.RegVar("RoomInfo", get_RoomInfo, set_RoomInfo);
		L.RegVar("HasNews", get_HasNews, null);
		L.RegVar("News", get_News, set_News);
		L.RegVar("HasActorId", get_HasActorId, null);
		L.RegVar("ActorId", get_ActorId, set_ActorId);
		L.RegVar("HasFrameId", get_HasFrameId, null);
		L.RegVar("FrameId", get_FrameId, set_FrameId);
		L.RegVar("HasRunInFrame", get_HasRunInFrame, null);
		L.RegVar("RunInFrame", get_RunInFrame, set_RunInFrame);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMyLib_GCPlayerCmd_Builder(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				MyLib.GCPlayerCmd.Builder obj = new MyLib.GCPlayerCmd.Builder();
				ToLua.PushSealed(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MyLib.GCPlayerCmd.Builder.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.GCPlayerCmd.Builder o = obj.Clear();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clone(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.GCPlayerCmd.Builder o = obj.Clone();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int BuildPartial(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.GCPlayerCmd o = obj.BuildPartial();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int MergeFrom(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<Google.ProtocolBuffers.IMessageLite>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				Google.ProtocolBuffers.IMessageLite arg0 = (Google.ProtocolBuffers.IMessageLite)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.MergeFrom(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<MyLib.GCPlayerCmd>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				MyLib.GCPlayerCmd arg0 = (MyLib.GCPlayerCmd)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.MergeFrom(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<Google.ProtocolBuffers.CodedInputStream>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				Google.ProtocolBuffers.CodedInputStream arg0 = (Google.ProtocolBuffers.CodedInputStream)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.MergeFrom(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<Google.ProtocolBuffers.ByteString>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				Google.ProtocolBuffers.ByteString arg0 = (Google.ProtocolBuffers.ByteString)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.MergeFrom(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<byte[]>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.MergeFrom(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.IO.Stream>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				System.IO.Stream arg0 = (System.IO.Stream)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.MergeFrom(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes<Google.ProtocolBuffers.CodedInputStream, Google.ProtocolBuffers.ExtensionRegistry>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				Google.ProtocolBuffers.CodedInputStream arg0 = (Google.ProtocolBuffers.CodedInputStream)ToLua.ToObject(L, 2);
				Google.ProtocolBuffers.ExtensionRegistry arg1 = (Google.ProtocolBuffers.ExtensionRegistry)ToLua.ToObject(L, 3);
				MyLib.GCPlayerCmd.Builder o = obj.MergeFrom(arg0, arg1);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes<Google.ProtocolBuffers.ByteString, Google.ProtocolBuffers.ExtensionRegistry>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				Google.ProtocolBuffers.ByteString arg0 = (Google.ProtocolBuffers.ByteString)ToLua.ToObject(L, 2);
				Google.ProtocolBuffers.ExtensionRegistry arg1 = (Google.ProtocolBuffers.ExtensionRegistry)ToLua.ToObject(L, 3);
				MyLib.GCPlayerCmd.Builder o = obj.MergeFrom(arg0, arg1);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes<byte[], Google.ProtocolBuffers.ExtensionRegistry>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
				Google.ProtocolBuffers.ExtensionRegistry arg1 = (Google.ProtocolBuffers.ExtensionRegistry)ToLua.ToObject(L, 3);
				MyLib.GCPlayerCmd.Builder o = obj.MergeFrom(arg0, arg1);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes<System.IO.Stream, Google.ProtocolBuffers.ExtensionRegistry>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				System.IO.Stream arg0 = (System.IO.Stream)ToLua.ToObject(L, 2);
				Google.ProtocolBuffers.ExtensionRegistry arg1 = (Google.ProtocolBuffers.ExtensionRegistry)ToLua.ToObject(L, 3);
				MyLib.GCPlayerCmd.Builder o = obj.MergeFrom(arg0, arg1);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: MyLib.GCPlayerCmd.Builder.MergeFrom");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetResult(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			string arg0 = ToLua.CheckString(L, 2);
			MyLib.GCPlayerCmd.Builder o = obj.SetResult(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearResult(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.GCPlayerCmd.Builder o = obj.ClearResult();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAvatarInfo(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<MyLib.AvatarInfo>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				MyLib.AvatarInfo arg0 = (MyLib.AvatarInfo)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.SetAvatarInfo(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<MyLib.AvatarInfo.Builder>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				MyLib.AvatarInfo.Builder arg0 = (MyLib.AvatarInfo.Builder)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.SetAvatarInfo(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: MyLib.GCPlayerCmd.Builder.SetAvatarInfo");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int MergeAvatarInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.AvatarInfo arg0 = (MyLib.AvatarInfo)ToLua.CheckObject(L, 2, typeof(MyLib.AvatarInfo));
			MyLib.GCPlayerCmd.Builder o = obj.MergeAvatarInfo(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearAvatarInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.GCPlayerCmd.Builder o = obj.ClearAvatarInfo();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetDamageInfo(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<MyLib.DamageInfo>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				MyLib.DamageInfo arg0 = (MyLib.DamageInfo)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.SetDamageInfo(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<MyLib.DamageInfo.Builder>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				MyLib.DamageInfo.Builder arg0 = (MyLib.DamageInfo.Builder)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.SetDamageInfo(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: MyLib.GCPlayerCmd.Builder.SetDamageInfo");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int MergeDamageInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.DamageInfo arg0 = (MyLib.DamageInfo)ToLua.CheckObject(L, 2, typeof(MyLib.DamageInfo));
			MyLib.GCPlayerCmd.Builder o = obj.MergeDamageInfo(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearDamageInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.GCPlayerCmd.Builder o = obj.ClearDamageInfo();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSkillAction(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<MyLib.SkillAction>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				MyLib.SkillAction arg0 = (MyLib.SkillAction)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.SetSkillAction(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<MyLib.SkillAction.Builder>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				MyLib.SkillAction.Builder arg0 = (MyLib.SkillAction.Builder)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.SetSkillAction(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: MyLib.GCPlayerCmd.Builder.SetSkillAction");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int MergeSkillAction(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.SkillAction arg0 = (MyLib.SkillAction)ToLua.CheckObject(L, 2, typeof(MyLib.SkillAction));
			MyLib.GCPlayerCmd.Builder o = obj.MergeSkillAction(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearSkillAction(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.GCPlayerCmd.Builder o = obj.ClearSkillAction();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetBuffInfo(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<MyLib.BuffInfo>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				MyLib.BuffInfo arg0 = (MyLib.BuffInfo)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.SetBuffInfo(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<MyLib.BuffInfo.Builder>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				MyLib.BuffInfo.Builder arg0 = (MyLib.BuffInfo.Builder)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.SetBuffInfo(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: MyLib.GCPlayerCmd.Builder.SetBuffInfo");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int MergeBuffInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.BuffInfo arg0 = (MyLib.BuffInfo)ToLua.CheckObject(L, 2, typeof(MyLib.BuffInfo));
			MyLib.GCPlayerCmd.Builder o = obj.MergeBuffInfo(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearBuffInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.GCPlayerCmd.Builder o = obj.ClearBuffInfo();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetEntityInfo(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<MyLib.EntityInfo>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				MyLib.EntityInfo arg0 = (MyLib.EntityInfo)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.SetEntityInfo(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<MyLib.EntityInfo.Builder>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				MyLib.EntityInfo.Builder arg0 = (MyLib.EntityInfo.Builder)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.SetEntityInfo(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: MyLib.GCPlayerCmd.Builder.SetEntityInfo");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int MergeEntityInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.EntityInfo arg0 = (MyLib.EntityInfo)ToLua.CheckObject(L, 2, typeof(MyLib.EntityInfo));
			MyLib.GCPlayerCmd.Builder o = obj.MergeEntityInfo(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearEntityInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.GCPlayerCmd.Builder o = obj.ClearEntityInfo();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetPickAction(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<MyLib.PickItemAction>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				MyLib.PickItemAction arg0 = (MyLib.PickItemAction)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.SetPickAction(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<MyLib.PickItemAction.Builder>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				MyLib.PickItemAction.Builder arg0 = (MyLib.PickItemAction.Builder)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.SetPickAction(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: MyLib.GCPlayerCmd.Builder.SetPickAction");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int MergePickAction(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.PickItemAction arg0 = (MyLib.PickItemAction)ToLua.CheckObject(L, 2, typeof(MyLib.PickItemAction));
			MyLib.GCPlayerCmd.Builder o = obj.MergePickAction(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearPickAction(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.GCPlayerCmd.Builder o = obj.ClearPickAction();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetLeftTime(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			MyLib.GCPlayerCmd.Builder o = obj.SetLeftTime(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearLeftTime(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.GCPlayerCmd.Builder o = obj.ClearLeftTime();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetRoomInfo(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<MyLib.RoomInfo>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				MyLib.RoomInfo arg0 = (MyLib.RoomInfo)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.SetRoomInfo(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<MyLib.RoomInfo.Builder>(L, 2))
			{
				MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
				MyLib.RoomInfo.Builder arg0 = (MyLib.RoomInfo.Builder)ToLua.ToObject(L, 2);
				MyLib.GCPlayerCmd.Builder o = obj.SetRoomInfo(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: MyLib.GCPlayerCmd.Builder.SetRoomInfo");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int MergeRoomInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.RoomInfo arg0 = (MyLib.RoomInfo)ToLua.CheckObject(L, 2, typeof(MyLib.RoomInfo));
			MyLib.GCPlayerCmd.Builder o = obj.MergeRoomInfo(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearRoomInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.GCPlayerCmd.Builder o = obj.ClearRoomInfo();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetNews(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			string arg0 = ToLua.CheckString(L, 2);
			MyLib.GCPlayerCmd.Builder o = obj.SetNews(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearNews(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.GCPlayerCmd.Builder o = obj.ClearNews();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetActorId(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			MyLib.GCPlayerCmd.Builder o = obj.SetActorId(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearActorId(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.GCPlayerCmd.Builder o = obj.ClearActorId();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetFrameId(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			ulong arg0 = LuaDLL.tolua_checkuint64(L, 2);
			MyLib.GCPlayerCmd.Builder o = obj.SetFrameId(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearFrameId(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.GCPlayerCmd.Builder o = obj.ClearFrameId();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetRunInFrame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			MyLib.GCPlayerCmd.Builder o = obj.SetRunInFrame(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearRunInFrame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)ToLua.CheckObject(L, 1, typeof(MyLib.GCPlayerCmd.Builder));
			MyLib.GCPlayerCmd.Builder o = obj.ClearRunInFrame();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DefaultInstanceForType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			MyLib.GCPlayerCmd ret = obj.DefaultInstanceForType;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index DefaultInstanceForType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HasResult(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			bool ret = obj.HasResult;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HasResult on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Result(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			string ret = obj.Result;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Result on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HasAvatarInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			bool ret = obj.HasAvatarInfo;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HasAvatarInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AvatarInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			MyLib.AvatarInfo ret = obj.AvatarInfo;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index AvatarInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HasDamageInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			bool ret = obj.HasDamageInfo;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HasDamageInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DamageInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			MyLib.DamageInfo ret = obj.DamageInfo;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index DamageInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HasSkillAction(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			bool ret = obj.HasSkillAction;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HasSkillAction on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SkillAction(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			MyLib.SkillAction ret = obj.SkillAction;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index SkillAction on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HasBuffInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			bool ret = obj.HasBuffInfo;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HasBuffInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BuffInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			MyLib.BuffInfo ret = obj.BuffInfo;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BuffInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HasEntityInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			bool ret = obj.HasEntityInfo;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HasEntityInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EntityInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			MyLib.EntityInfo ret = obj.EntityInfo;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index EntityInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HasPickAction(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			bool ret = obj.HasPickAction;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HasPickAction on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PickAction(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			MyLib.PickItemAction ret = obj.PickAction;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index PickAction on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HasLeftTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			bool ret = obj.HasLeftTime;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HasLeftTime on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LeftTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			int ret = obj.LeftTime;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LeftTime on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HasRoomInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			bool ret = obj.HasRoomInfo;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HasRoomInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RoomInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			MyLib.RoomInfo ret = obj.RoomInfo;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index RoomInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HasNews(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			bool ret = obj.HasNews;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HasNews on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_News(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			string ret = obj.News;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index News on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HasActorId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			bool ret = obj.HasActorId;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HasActorId on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ActorId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			int ret = obj.ActorId;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ActorId on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HasFrameId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			bool ret = obj.HasFrameId;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HasFrameId on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FrameId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			ulong ret = obj.FrameId;
			LuaDLL.tolua_pushuint64(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index FrameId on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HasRunInFrame(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			bool ret = obj.HasRunInFrame;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HasRunInFrame on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RunInFrame(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			int ret = obj.RunInFrame;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index RunInFrame on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Result(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.Result = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Result on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AvatarInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			MyLib.AvatarInfo arg0 = (MyLib.AvatarInfo)ToLua.CheckObject(L, 2, typeof(MyLib.AvatarInfo));
			obj.AvatarInfo = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index AvatarInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_DamageInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			MyLib.DamageInfo arg0 = (MyLib.DamageInfo)ToLua.CheckObject(L, 2, typeof(MyLib.DamageInfo));
			obj.DamageInfo = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index DamageInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SkillAction(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			MyLib.SkillAction arg0 = (MyLib.SkillAction)ToLua.CheckObject(L, 2, typeof(MyLib.SkillAction));
			obj.SkillAction = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index SkillAction on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BuffInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			MyLib.BuffInfo arg0 = (MyLib.BuffInfo)ToLua.CheckObject(L, 2, typeof(MyLib.BuffInfo));
			obj.BuffInfo = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BuffInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_EntityInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			MyLib.EntityInfo arg0 = (MyLib.EntityInfo)ToLua.CheckObject(L, 2, typeof(MyLib.EntityInfo));
			obj.EntityInfo = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index EntityInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_PickAction(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			MyLib.PickItemAction arg0 = (MyLib.PickItemAction)ToLua.CheckObject(L, 2, typeof(MyLib.PickItemAction));
			obj.PickAction = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index PickAction on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LeftTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.LeftTime = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LeftTime on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_RoomInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			MyLib.RoomInfo arg0 = (MyLib.RoomInfo)ToLua.CheckObject(L, 2, typeof(MyLib.RoomInfo));
			obj.RoomInfo = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index RoomInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_News(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.News = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index News on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ActorId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.ActorId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ActorId on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_FrameId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			ulong arg0 = LuaDLL.tolua_checkuint64(L, 2);
			obj.FrameId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index FrameId on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_RunInFrame(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MyLib.GCPlayerCmd.Builder obj = (MyLib.GCPlayerCmd.Builder)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.RunInFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index RunInFrame on a nil value");
		}
	}
}

